name: Build

# Trigger only when manually requested
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Makefile
        run: make --always-make TARGET=X86
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mini-asm
          path: mini-asm.exe
