name: Build

# Trigger only when manually requested
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build EXE
        run: gcc -I./src -o mini-asm.exe src/*.c
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mini-asm
          path: mini-asm.exe
